services:
  db:
    image: postgres:14-alpine
    container_name: ai_navi_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ainavi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    # ★★★ このコマンドを修正: --threads 2 を削除 ★★★
    command: gunicorn --workers 2 --worker-class gevent --timeout 120 --bind 0.0.0.0:5000 "app:create_app()"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
